site_name: MARGARITA
nav:
  - 📚 Documentation:
    - Getting Started:
      - MARGARITA: index.md
      - Hello Margarita: hello.md
    - Language Reference:
        - Overview: mgx.md
        - Running the Agent: running_the_agent.md
        - Markdown: markdown.md
        - Conditionals: conditionals.md
        - State: state.md
        - Loops: loops.md
        - Variables: variables.md
        - Metadata: metadata.md
        - .mg files: mg.md
        - Includes: include_files.md
        - Contexts: contexts.md
        - Context Management: context_management.md
        - User Input: user_input.md
        - Logging: logging.md
        - Memory: memory.md
        - Stopping the Agent: stopping.md
        - Function Calls: function_calls.md
        - Custom Tools: custom_tools.md
        - Sub Runs: sub_runs.md
        - Await All: await_all.md
        - Prompt Locking: prompt_locking.md
        - Plugins: coming_soon.md
  - Other Tools:
      - Template Packages in your .venv: uv_packages.md
      - Claude Skill: claude_skill.md
      - Jetbrains IDE Plugin: jetbrains_plugin.md
  - Python API:
      - Basic Usage: basic.md
      - Includes For Organized Prompts: includes.md
      - Agentic Loops: use-in-agents.md

repo_url: https://github.com/banyango/margarita
repo_name: banyango/margarita
theme:
  icon:
    logo: material/puzzle
  name: material
  custom_dir: overrides
  features:
    - search.highlight
    - navigation.sections
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
  font:
    code: JetBrains Mono
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/link
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/toggle-switch-off
          name: Switch to system preference
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - toc:
      permalink: true
plugins:
  - mike
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [".."]
          options:
            group_by_category: true
            show_category_heading: true
            docstring_style: sphinx
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
hooks:
  - hooks.py
extra_css:
  - stylesheets/extra.css
docs_dir: pages
extra:
  version:
    provider: mike
